apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd 
spec:
  destination:
    namespace: crossplane
    server: https://kubernetes.default.svc
  project: argo-cd-ready-applications
  source:
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.9.2
    chart: crossplane
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true